extraction_parameters:
  feature_keys: True
  num_samples: null
  model_complexity: 2
  min_detection_confidence: 0.9
  min_tracking_confidence: 0.9

processing_parameters:
  data_used_fraction: 0.1
  num_iterations: 3
